// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/modal": {
    params: {};
  };
  "/product": {
    params: {};
  };
  "/category": {
    params: {};
  };
  "/examples": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/cart" | "/modal" | "/product" | "/category" | "/examples" | "/login" | "/profile" | "/*";
  };
  "./pages/home/index.ts": {
    id: "pages/home/index";
    page: "/";
  };
  "pages/cart/index.ts": {
    id: "pages/cart/index";
    page: "/cart";
  };
  "pages/modal/index.ts": {
    id: "pages/modal/index";
    page: "/modal";
  };
  "pages/product/index.ts": {
    id: "pages/product/index";
    page: "/product";
  };
  "pages/category/index.ts": {
    id: "pages/category/index";
    page: "/category";
  };
  "pages/examples/index.ts": {
    id: "pages/examples/index";
    page: "/examples";
  };
  "pages/login/index.ts": {
    id: "pages/login/index";
    page: "/login";
  };
  "pages/profile/index.ts": {
    id: "pages/profile/index";
    page: "/profile";
  };
  "./pages/not-found/index.ts": {
    id: "pages/not-found/index";
    page: "/*";
  };
};